GRANT USAGE ON SCHEMA mediacentre TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA mediacentre TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA mediacentre TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA mediacentre TO "apps";